Added tests and updated requirements
dpeerlab/PhenoGraph pull request #8
Opened 2020-09-18 02:28 UTC by armMSKCC

requirements.txt now includes update to scipy and leidenalg

new tests folder added with 7 unit tests for functions which rely on scipy/leidenalg

cluster function in cluster.py refactored to separate community detection functions for testing

Note: Maybe we should create a "version 1.5.7" branch as mentioned?

2020-09-28 16:21 UTC, hisplan commented
I see two `RB_genes_human.txt`. Let's remove one of them. Maybe keep the one in the `data` folder?

2020-09-29 22:28 UTC, hisplan commented
Hmm. I'm not sure if your 1.5.7 branch is fully synced with dpeerlab:1.5.7.

2020-09-30 15:56 UTC, armMSKCC commented
Should be okay now

2020-09-30 17:39 UTC, hisplan commented
@armMSKCC a few comments:

Code
- Bump up the version to 1.5.7 in `version.py`
- Run Black on `test_cluster.py` (https://github.com/psf/black). You can also run this from VS Code or PyCharm.

Notebook
- Change Phenograph to PhenoGraph.
- Add `phenograph.__version__` to display PhenoGraph version along with Scanpy versions.
- `pip install scanpy==1.6.0` - the notebook might not run with the old versions.
- Rename `Phenograph_tutorial.ipynb` to `tutorial-pbmc3k.ipynb`
- Rename `example-01-using-random-data-points.ipynb` to `example-using-random-data-points.ipynb`

README.md
- Update release notes.
- Add a new section and describe how one can run pytest and resolve the issue we encountered.
- Mention and add a link to the new tutorial.

2020-09-30 18:29 UTC, hisplan commented
@armMSKCC Forgot one thing. The notebook failed to load the RB file.

2020-09-30 20:00 UTC, hisplan requested changes
Minor comments

2020-09-30 20:00 UTC, hisplan commented on README.md
> +* Updated leidenalg and scipy version requirements, revised parallel jaccard to support scipy==1.5.1, and created a test collection for use with pytest (see above)
"see above" --> "see below" you mean? Maybe make a link to the unit test section?

2020-09-30 20:00 UTC, hisplan commented on README.md
> +    python --version
Put this into a preformatted box like this:
```
python --version
```

2020-09-30 20:01 UTC, hisplan commented
I still don't see these in the Jupyter notebook:
- Add `phenograph.__version__` to display PhenoGraph version along with Scanpy versions.
- `!pip install scanpy==1.6.0` - the notebook might not run with the old versions.

2020-09-30 22:54 UTC, merged